### PR TITLE
Fixed HTML validation failures by providing an Action for the form

### PR DESCRIPTION
**Pull request by AndrewGorton**
Gave the form a non-empty Action so HTML Validation doesn't complain.

### CODE REVIEW

**Comment by camillebaldock** [comment]
Looking at build failures caused by a gem missing on Jenkins :) nothing wrong with this code

**Comment by camillebaldock** [comment]
can you mark yourself as working on https://www.pivotaltracker.com/story/show/90276116 just to make sure no-one else picks it up since you're on it? thanks!

**Comment by AndrewGorton** [comment]
Have marked it thusly.

**Comment by Demotive** [comment]
:+1:

**Pull request merged**
