### PR TITLE
Display price paid/stated information

### PR DESCRIPTION
**Pull request by camillebaldock**
Fixes some CSS/HTML issues

### CODE REVIEW

**Comment by russwillis** [comment]
I see you also changed the way we display proprietors (owners and lenders). Is that part of the story or just a general tidy up. Should we amend code that's not directly part of the story?
Code all good :)

**Comment by camillebaldock** [comment]
@russwillis this is minor refactoring as we go along, to align ourselves to the prototype design :) the design looked particularly terrible with multiple lenders or proprietors

## Before

(Integration environment screenshot, with bogus test data)

screen shot 2015-06-01 at 14 07 38

## After

(Dev environment screenshot)

screen shot 2015-06-01 at 14 04 42

**Comment by lgonczar** [comment]
Looks good to me

**Comment by camillebaldock** [comment]
:warning: to be merged with https://github.com/LandRegistry/digital-register-feeder/pull/135 :)

**Pull request merged**
